Select * from stormdemodb.Countries;
CREATE TABLE `Countries` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


Select * from stormdemodb.Candidates;
CREATE TABLE `Candidates` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;



Select * from stormdemodb.States;
CREATE TABLE `States` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


CREATE TABLE `StateCandidates` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `STATE` varchar(45) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

CREATE TABLE `HashTagCandidates` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HASHTAG` varchar(45) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;


CREATE TABLE `HashTagStates` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HASHTAG` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

CREATE TABLE `HashTags` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `HASHTAG` varchar(45) NOT NULL,
  `COUNT` int(11) DEFAULT NULL,
  `REC_CREN_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;
